theme: jekyll-theme-hacker
github: [metadata]
title: "MosheF Dev Blog"
description: "Spread the Code"
disqus: 'moshfeu-github-io.disqus.com'
show_downloads: false
author: 'MosheF'
add_this_share: '516a7ca844f07801'
excerpt_separator: '<!--more-->'
google_analytics: 'UA-118358576-1'
plugins:
  - jekyll-sitemap